# Generated by Django 6.0 on 2026-02-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="juego",
            name="imagen",
            field=models.CharField(default="default.png", max_length=200),
        ),
    ]
